
version: '3.8'

services:
  # Frontend React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    environment:
      - VITE_API_URL=/api
    restart: unless-stopped

  # Backend API Server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/wildstore
      - PORT=3000
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET:-your_secure_jwt_secret_key}
      - CORS_ORIGIN=http://localhost:80,http://frontend:80
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  # MongoDB Database
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=wildstore

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
